settings:
  legacy:
    force: false
    interval: 0s
schema:
  - name: oscrud
    path: example/
    commands:
      install:
        status: true
        method: go install
      run:
        status: true
    watcher:
      extensions:
        - go
      paths:
        - .
      ignored_paths:
        - .git
        - .realize
